/**
 * Fix the thermal-printed/archival paper reference in items.json
 * Thermal paper is NOT archival — it fades in months, especially in radiation.
 */
import { decodeObject, encodeObject } from '../src/encoding';
import * as fs from 'fs';

const fp = 'src/data/items.json';
const raw = JSON.parse(fs.readFileSync(fp, 'utf-8'));
const decoded = decodeObject(raw);

const items = decoded.items as Array<Record<string, unknown>>;
let fixed = 0;
for (const item of items) {
  if (typeof item.description === 'string' && item.description.includes('thermal-printed pages')) {
    const old = item.description;
    item.description = item.description
      .replace(
        'A sheaf of thermal-printed pages, the kind generated by the ship\'s automated maintenance logging system. The paper has the slightly waxy feel of archival stock, designed to last for decades without degrading.',
        'A sheaf of electrostatically printed pages on synthetic polymer stock — the kind generated by the ship\'s automated maintenance logging system. The material is engineered to resist UV degradation, radiation embrittlement, and chemical exposure for centuries. It feels like thin plastic rather than paper.'
      );
    process.stdout.write(`FIXED description:\n  OLD: ${old.substring(0, 200)}...\n  NEW: ${(item.description as string).substring(0, 200)}...\n\n`);
    fixed++;
  }
}

if (fixed > 0) {
  const encoded = encodeObject(decoded);
  fs.writeFileSync(fp, JSON.stringify(encoded, null, 2) + '\n', 'utf-8');
  process.stdout.write(`Wrote ${fixed} fix(es) to ${fp}\n`);
} else {
  process.stdout.write('No matches found to fix.\n');
}
